# Generated by Django 3.1.2 on 2021-02-26 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Embedder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vector_length', models.PositiveSmallIntegerField()),
                ('precision', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.artist')),
                ('licenses', models.ManyToManyField(related_name='songs', to='vectorsearch.License')),
            ],
        ),
        migrations.CreateModel(
            name='ResultVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('embedder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.embedder')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryVector',
            fields=[
                ('vector', models.JSONField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vectorsearch.embedder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.artist'),
        ),
    ]
