# Generated by Django 3.1.2 on 2021-02-26 23:31

from django.db import migrations, models
import vectorsearch.utils.json_tools


class Migration(migrations.Migration):

    dependencies = [
        ('vectorsearch', '0002_auto_20210226_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryvector',
            name='vector',
            field=models.JSONField(encoder=vectorsearch.utils.json_tools.NumpyEncoder),
        ),
        migrations.AlterField(
            model_name='resultvector',
            name='vector',
            field=models.JSONField(encoder=vectorsearch.utils.json_tools.NumpyEncoder),
        ),
    ]
