# Generated by Django 3.1.2 on 2021-02-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vectorsearch', '0003_auto_20210226_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectorsearch.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embedder',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embedder',
            name='precision',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='embedder',
            name='vector_length',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='abbreviation',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='resultvector',
            name='embedder',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.embedder'),
        ),
        migrations.AlterField(
            model_name='resultvector',
            name='song',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vectorsearch.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectorsearch.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectorsearch.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='external_url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='licenses',
            field=models.ManyToManyField(editable=False, related_name='songs', to='vectorsearch.License'),
        ),
    ]
