# Generated by Django 3.1.2 on 2021-02-26 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vectorsearch', '0004_auto_20210226_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryvector',
            name='spectrogram_hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='queryvector',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
